namespace Hamfer.WebApi.Core.ContentTypes;

// Image or graphical data including both bitmap and vector still images as well as animated versions of still image formats such as animated GIF or APNG.
// https://developer.mozilla.org/en-US/docs/Web/Media/Guides/Formats/Image_types#common_image_file_types
// https://www.iana.org/assignments/media-types/media-types.xhtml#image
// To use csv: ^([^,]+),(image/[a-z0-9+-_]+),(.+)$	=>	\t"$1": "$2",\t\t// '$1' from reference $3
// last updated as 2025-12-25
public static class ImageContentType
{
	public static readonly Dictionary<string, string> ContentTypes = new()
	{
		{"aces", "image/aces"},		// 'aces' from reference [SMPTE][Howard_Lukk]
    {"apng", "image/apng"},		// 'apng' from reference [W3C][W3C_PNG_WG]
    {"avci", "image/avci"},		// 'avci' from reference [ISO-IEC_JTC_1][David_Singer]
    {"avcs", "image/avcs"},		// 'avcs' from reference [ISO-IEC_JTC_1][David_Singer]
    {"avif", "image/avif"},		// 'avif' from reference [Alliance_for_Open_Media][Cyril_Concolato]
    {"bmp", "image/bmp"},		// 'bmp' from reference [RFC7903]
    {"cgm", "image/cgm"},		// 'cgm' from reference [Alan_Francis]
    {"dicom-rle", "image/dicom-rle"},		// 'dicom-rle' from reference [DICOM_Standard_Committee][David_Clunie]
    {"dpx", "image/dpx"},		// 'dpx' from reference [SMPTE][SMPTE_Director_of_Standards_Development]
    {"emf", "image/emf"},		// 'emf' from reference [RFC7903]
    {"example", "image/example"},		// 'example' from reference [RFC4735]
    {"fits", "image/fits"},		// 'fits' from reference [RFC4047]
    {"g3fax", "image/g3fax"},		// 'g3fax' from reference [RFC1494]
    {"gif", "image/gif"},		// 'gif' from reference [RFC2045][RFC2046]
    {"heic", "image/heic"},		// 'heic' from reference [ISO-IEC_JTC_1][David_Singer]
    {"heic-sequence", "image/heic-sequence"},		// 'heic-sequence' from reference [ISO-IEC_JTC_1][David_Singer]
    {"heif", "image/heif"},		// 'heif' from reference [ISO-IEC_JTC_1][David_Singer]
    {"heif-sequence", "image/heif-sequence"},		// 'heif-sequence' from reference [ISO-IEC_JTC_1][David_Singer]
    {"hej2k", "image/hej2k"},		// 'hej2k' from reference [ISO-IEC_JTC_1][ITU-T]
    {"hsj2 (OBSOLETE)", "image/hsj2"},		// 'hsj2 (OBSOLETE)' from reference [ISO-IEC_JTC_1][ITU-T]
    {"ief", "image/ief"},		// 'ief' from reference [RFC1314]
    {"j2c", "image/j2c"},		// 'j2c' from reference [ISO-IEC_JTC_1_SC_29_WG_1][ISO-IEC_JTC_1][ITU-T]
    {"jaii", "image/jaii"},		// 'jaii' from reference [ISO-IEC_JTC_1_SC_29_WG_1][Ye-Kui_Wang]
    {"jais", "image/jais"},		// 'jais' from reference [ISO-IEC_JTC_1_SC_29_WG_1][Ye-Kui_Wang]
    {"jls", "image/jls"},		// 'jls' from reference [DICOM_Standard_Committee][David_Clunie]
    {"jp2", "image/jp2"},		// 'jp2' from reference [RFC3745]
    {"jpeg", "image/jpeg"},		// 'jpeg' from reference [RFC2045][RFC2046]
    {"jph", "image/jph"},		// 'jph' from reference [ISO-IEC_JTC_1][ITU-T]
    {"jphc", "image/jphc"},		// 'jphc' from reference [ISO-IEC_JTC_1][ITU-T]
    {"jpm", "image/jpm"},		// 'jpm' from reference [RFC3745]
    {"jpx", "image/jpx"},		// 'jpx' from reference [RFC3745][ISO-IEC_JTC_1_SC_29_WG_1]
    {"jxl", "image/jxl"},		// 'jxl' from reference [ISO-IEC_JTC_1_SC_29_WG_1][ISO-IEC_JTC_1]
    {"jxr", "image/jxr"},		// 'jxr' from reference [ISO-IEC_JTC_1][ITU-T]
    {"jxrA", "image/jxrA"},		// 'jxrA' from reference [ISO-IEC_JTC_1][ITU-T]
    {"jxrS", "image/jxrS"},		// 'jxrS' from reference [ISO-IEC_JTC_1][ITU-T]
    {"jxs", "image/jxs"},		// 'jxs' from reference [ISO-IEC_JTC_1]
    {"jxsc", "image/jxsc"},		// 'jxsc' from reference [ISO-IEC_JTC_1]
    {"jxsi", "image/jxsi"},		// 'jxsi' from reference [ISO-IEC_JTC_1]
    {"jxss", "image/jxss"},		// 'jxss' from reference [ISO-IEC_JTC_1]
    {"ktx", "image/ktx"},		// 'ktx' from reference [Khronos][Mark_Callow]
    {"ktx2", "image/ktx2"},		// 'ktx2' from reference [Khronos][Mark_Callow]
    {"naplps", "image/naplps"},		// 'naplps' from reference [Ilya_Ferber]
    {"png", "image/png"},		// 'png' from reference [W3C][PNG_WG][PNG]
    {"prs.btif", "image/prs.btif"},		// 'prs.btif' from reference [Ben_Simon]
    {"prs.pti", "image/prs.pti"},		// 'prs.pti' from reference [Juern_Laun]
    {"pwg-raster", "image/pwg-raster"},		// 'pwg-raster' from reference [Michael_Sweet]
    {"svg+xml", "image/svg+xml"},		// 'svg+xml' from reference [W3C][http://www.w3.org/TR/SVG/mimereg.html]
    {"t38", "image/t38"},		// 't38' from reference [RFC3362]
    {"tiff", "image/tiff"},		// 'tiff' from reference [RFC3302]
    {"tiff-fx", "image/tiff-fx"},		// 'tiff-fx' from reference [RFC3950]
    {"vnd.adobe.photoshop", "image/vnd.adobe.photoshop"},		// 'vnd.adobe.photoshop' from reference [Kim_Scarborough]
    {"vnd.airzip.accelerator.azv", "image/vnd.airzip.accelerator.azv"},		// 'vnd.airzip.accelerator.azv' from reference [Gary_Clueit]
    {"vnd.blockfact.facti", "image/vnd.blockfact.facti"},		// 'vnd.blockfact.facti' from reference [Egbert_von_Frankenberg]
    {"vnd.clip", "image/vnd.clip"},		// 'vnd.clip' from reference [Ryo_Inaba]
    {"vnd.cns.inf2", "image/vnd.cns.inf2"},		// 'vnd.cns.inf2' from reference [Ann_McLaughlin]
    {"vnd.dece.graphic", "image/vnd.dece.graphic"},		// 'vnd.dece.graphic' from reference [Michael_A_Dolan]
    {"vnd.djvu", "image/vnd.djvu"},		// 'vnd.djvu' from reference [Leon_Bottou]
    {"vnd.dwg", "image/vnd.dwg"},		// 'vnd.dwg' from reference [Jodi_Moline]
    {"vnd.dxf", "image/vnd.dxf"},		// 'vnd.dxf' from reference [Jodi_Moline]
    {"vnd.dvb.subtitle", "image/vnd.dvb.subtitle"},		// 'vnd.dvb.subtitle' from reference [Peter_Siebert][Michael_Lagally]
    {"vnd.fastbidsheet", "image/vnd.fastbidsheet"},		// 'vnd.fastbidsheet' from reference [Scott_Becker]
    {"vnd.fpx", "image/vnd.fpx"},		// 'vnd.fpx' from reference [Marc_Douglas_Spencer]
    {"vnd.fst", "image/vnd.fst"},		// 'vnd.fst' from reference [Arild_Fuldseth]
    {"vnd.fujixerox.edmics-mmr", "image/vnd.fujixerox.edmics-mmr"},		// 'vnd.fujixerox.edmics-mmr' from reference [Masanori_Onda]
    {"vnd.fujixerox.edmics-rlc", "image/vnd.fujixerox.edmics-rlc"},		// 'vnd.fujixerox.edmics-rlc' from reference [Masanori_Onda]
    {"vnd.globalgraphics.pgb", "image/vnd.globalgraphics.pgb"},		// 'vnd.globalgraphics.pgb' from reference [Martin_Bailey]
    {"vnd.microsoft.icon", "image/vnd.microsoft.icon"},		// 'vnd.microsoft.icon' from reference [Simon_Butcher]
    {"vnd.mix", "image/vnd.mix"},		// 'vnd.mix' from reference [Saveen_Reddy]
    {"vnd.ms-modi", "image/vnd.ms-modi"},		// 'vnd.ms-modi' from reference [Gregory_Vaughan]
    {"vnd.mozilla.apng", "image/vnd.mozilla.apng"},		// 'vnd.mozilla.apng' from reference [Stuart_Parmenter]
    {"vnd.net-fpx", "image/vnd.net-fpx"},		// 'vnd.net-fpx' from reference [Marc_Douglas_Spencer]
    {"vnd.pco.b16", "image/vnd.pco.b16"},		// 'vnd.pco.b16' from reference [PCO_AG][Jan_Zeman]
    {"vnd.radiance", "image/vnd.radiance"},		// 'vnd.radiance' from reference [Randolph_Fritz][Greg_Ward]
    {"vnd.sealed.png", "image/vnd.sealed.png"},		// 'vnd.sealed.png' from reference [David_Petersen]
    {"vnd.sealedmedia.softseal.gif", "image/vnd.sealedmedia.softseal.gif"},		// 'vnd.sealedmedia.softseal.gif' from reference [David_Petersen]
    {"vnd.sealedmedia.softseal.jpg", "image/vnd.sealedmedia.softseal.jpg"},		// 'vnd.sealedmedia.softseal.jpg' from reference [David_Petersen]
    {"vnd.svf", "image/vnd.svf"},		// 'vnd.svf' from reference [Jodi_Moline]
    {"vnd.tencent.tap", "image/vnd.tencent.tap"},		// 'vnd.tencent.tap' from reference [Ni_Hui]
    {"vnd.valve.source.texture", "image/vnd.valve.source.texture"},		// 'vnd.valve.source.texture' from reference [Henrik_Andersson]
    {"vnd.wap.wbmp", "image/vnd.wap.wbmp"},		// 'vnd.wap.wbmp' from reference [Peter_Stark]
    {"vnd.xiff", "image/vnd.xiff"},		// 'vnd.xiff' from reference [Steven_Martin]
    {"vnd.zbrush.pcx", "image/vnd.zbrush.pcx"},		// 'vnd.zbrush.pcx' from reference [Chris_Charabaruk]
    {"webp", "image/webp"},		// 'webp' from reference [RFC9649]
    {"wmf", "image/wmf"},		// 'wmf' from reference [RFC7903]
    {"x-emf - DEPRECATED in favor of image/emf", "image/x-emf"},		// 'x-emf - DEPRECATED in favor of image/emf' from reference [RFC7903]
    {"x-wmf - DEPRECATED in favor of image/wmf", "image/x-wmf"},		// 'x-wmf - DEPRECATED in favor of image/wmf' from reference [RFC7903]
	};
}