namespace Hamfer.WebApi.Core.ContentTypes;

// Text-only data including any human-readable content, source code, or textual data such as comma-separated value (CSV) formatted data.
// https://www.iana.org/assignments/media-types/media-types.xhtml#text
// To use csv: ^([^,]+),(text/[a-z0-9+-_]+),(.+)$	=>	\t"$1": "$2",\t\t// '$1' from reference $3
// last updated as 2025-12-25
public static class TextContentType
{
	public static readonly Dictionary<string, string> ContentTypes = new()
	{
    {"1d-interleaved-parityfec", "text/1d-interleaved-parityfec"},		// '1d-interleaved-parityfec' from reference [RFC6015]
    {"cache-manifest", "text/cache-manifest"},		// 'cache-manifest' from reference [W3C][Robin_Berjon]
    {"calendar", "text/calendar"},		// 'calendar' from reference [RFC5545]
    {"cql", "text/cql"},		// 'cql' from reference [HL7][Bryn_Rhodes]
    {"cql-expression", "text/cql-expression"},		// 'cql-expression' from reference [HL7][Bryn_Rhodes]
    {"cql-identifier", "text/cql-identifier"},		// 'cql-identifier' from reference [HL7][Bryn_Rhodes]
    {"css", "text/css"},		// 'css' from reference [RFC2318]
    {"csv", "text/csv"},		// 'csv' from reference [RFC4180][RFC7111]
    {"csv-schema", "text/csv-schema"},		// 'csv-schema' from reference [National_Archives_UK][David_Underdown]
    {"directory - DEPRECATED by RFC6350", "text/directory"},		// 'directory - DEPRECATED by RFC6350' from reference [RFC2425][RFC6350]
    {"dns", "text/dns"},		// 'dns' from reference [RFC4027]
    {"ecmascript (OBSOLETED in favor of text/javascript)", "text/ecmascript"},		// 'ecmascript (OBSOLETED in favor of text/javascript)' from reference [RFC9239]
    {"encaprtp", "text/encaprtp"},		// 'encaprtp' from reference [RFC6849]
    {"enriched", "text/enriched"},		// 'enriched' from reference [RFC1896]
    {"example", "text/example"},		// 'example' from reference [RFC4735]
    {"fhirpath", "text/fhirpath"},		// 'fhirpath' from reference [HL7][Bryn_Rhodes]
    {"flexfec", "text/flexfec"},		// 'flexfec' from reference [RFC8627]
    {"fwdred", "text/fwdred"},		// 'fwdred' from reference [RFC6354]
    {"gff3", "text/gff3"},		// 'gff3' from reference [Sequence_Ontology]
    {"grammar-ref-list", "text/grammar-ref-list"},		// 'grammar-ref-list' from reference [RFC6787]
    {"hl7v2", "text/hl7v2"},		// 'hl7v2' from reference [HL7][Marc_Duteau]
    {"html", "text/html"},		// 'html' from reference [W3C][Robin_Berjon]
    {"javascript", "text/javascript"},		// 'javascript' from reference [RFC9239]
    {"jcr-cnd", "text/jcr-cnd"},		// 'jcr-cnd' from reference [Peeter_Piegaze]
    {"markdown", "text/markdown"},		// 'markdown' from reference [RFC7763]
    {"mizar", "text/mizar"},		// 'mizar' from reference [Jesse_Alama]
    {"n3", "text/n3"},		// 'n3' from reference [W3C][Eric_Prudhommeaux]
    {"org", "text/org"},		// 'org' from reference [Org_Mode][Jeffrey_Gipson][4]
    {"parameters", "text/parameters"},		// 'parameters' from reference [RFC7826]
    {"parityfec", "text/parityfec"},		// 'parityfec' from reference [RFC3009]
    {"plain", "text/plain"},		// 'plain' from reference [RFC2046][RFC3676][RFC5147]
    {"provenance-notation", "text/provenance-notation"},		// 'provenance-notation' from reference [W3C][Ivan_Herman]
    {"prs.fallenstein.rst", "text/prs.fallenstein.rst"},		// 'prs.fallenstein.rst' from reference [Benja_Fallenstein]
    {"prs.lines.tag", "text/prs.lines.tag"},		// 'prs.lines.tag' from reference [John_Lines]
    {"prs.prop.logic", "text/prs.prop.logic"},		// 'prs.prop.logic' from reference [Hans-Dieter_A._Hiep]
    {"prs.texi", "text/prs.texi"},		// 'prs.texi' from reference [Matin_Bavardi]
    {"raptorfec", "text/raptorfec"},		// 'raptorfec' from reference [RFC6682]
    {"RED", "text/RED"},		// 'RED' from reference [RFC4102]
    {"rfc822-headers", "text/rfc822-headers"},		// 'rfc822-headers' from reference [RFC6522]
    {"richtext", "text/richtext"},		// 'richtext' from reference [RFC2045][RFC2046]
    {"rtf", "text/rtf"},		// 'rtf' from reference [Paul_Lindner]
    {"rtp-enc-aescm128", "text/rtp-enc-aescm128"},		// 'rtp-enc-aescm128' from reference [_3GPP]
    {"rtploopback", "text/rtploopback"},		// 'rtploopback' from reference [RFC6849]
    {"rtx", "text/rtx"},		// 'rtx' from reference [RFC4588]
    {"SGML", "text/SGML"},		// 'SGML' from reference [RFC1874]
    {"shaclc", "text/shaclc"},		// 'shaclc' from reference [W3C_SHACL_Community_Group][Vladimir_Alexiev]
    {"shex", "text/shex"},		// 'shex' from reference [W3C][Eric_Prudhommeaux]
    {"spdx", "text/spdx"},		// 'spdx' from reference [Linux_Foundation][Rose_Judge]
    {"strings", "text/strings"},		// 'strings' from reference [IEEE-ISTO-PWG-PPP]
    {"t140", "text/t140"},		// 't140' from reference [RFC4103]
    {"tab-separated-values", "text/tab-separated-values"},		// 'tab-separated-values' from reference [Paul_Lindner]
    {"troff", "text/troff"},		// 'troff' from reference [RFC4263]
    {"turtle", "text/turtle"},		// 'turtle' from reference [W3C][Eric_Prudhommeaux]
    {"ulpfec", "text/ulpfec"},		// 'ulpfec' from reference [RFC5109]
    {"uri-list", "text/uri-list"},		// 'uri-list' from reference [RFC2483]
    {"vcard", "text/vcard"},		// 'vcard' from reference [RFC6350]
    {"vnd.a", "text/vnd.a"},		// 'vnd.a' from reference [Regis_Dehoux]
    {"vnd.abc", "text/vnd.abc"},		// 'vnd.abc' from reference [Steve_Allen]
    {"vnd.ascii-art", "text/vnd.ascii-art"},		// 'vnd.ascii-art' from reference [Kim_Scarborough]
    {"vnd.curl", "text/vnd.curl"},		// 'vnd.curl' from reference [Robert_Byrnes]
    {"vnd.debian.copyright", "text/vnd.debian.copyright"},		// 'vnd.debian.copyright' from reference [Charles_Plessy]
    {"vnd.DMClientScript", "text/vnd.DMClientScript"},		// 'vnd.DMClientScript' from reference [Dan_Bradley]
    {"vnd.dvb.subtitle", "text/vnd.dvb.subtitle"},		// 'vnd.dvb.subtitle' from reference [Peter_Siebert][Michael_Lagally]
    {"vnd.esmertec.theme-descriptor", "text/vnd.esmertec.theme-descriptor"},		// 'vnd.esmertec.theme-descriptor' from reference [Stefan_Eilemann]
    {"vnd.exchangeable", "text/vnd.exchangeable"},		// 'vnd.exchangeable' from reference [Martin_Cizek]
    {"vnd.familysearch.gedcom", "text/vnd.familysearch.gedcom"},		// 'vnd.familysearch.gedcom' from reference [Gordon_Clarke]
    {"vnd.ficlab.flt", "text/vnd.ficlab.flt"},		// 'vnd.ficlab.flt' from reference [Steve_Gilberd]
    {"vnd.fly", "text/vnd.fly"},		// 'vnd.fly' from reference [John-Mark_Gurney]
    {"vnd.fmi.flexstor", "text/vnd.fmi.flexstor"},		// 'vnd.fmi.flexstor' from reference [Kari_E._Hurtta]
    {"vnd.gml", "text/vnd.gml"},		// 'vnd.gml' from reference [Mi_Tar]
    {"vnd.graphviz", "text/vnd.graphviz"},		// 'vnd.graphviz' from reference [John_Ellson]
    {"vnd.hans", "text/vnd.hans"},		// 'vnd.hans' from reference [Hill_Hanxv]
    {"vnd.hgl", "text/vnd.hgl"},		// 'vnd.hgl' from reference [Heungsub_Lee]
    {"vnd.in3d.3dml", "text/vnd.in3d.3dml"},		// 'vnd.in3d.3dml' from reference [Michael_Powers]
    {"vnd.in3d.spot", "text/vnd.in3d.spot"},		// 'vnd.in3d.spot' from reference [Michael_Powers]
    {"vnd.IPTC.NewsML", "text/vnd.IPTC.NewsML"},		// 'vnd.IPTC.NewsML' from reference [IPTC]
    {"vnd.IPTC.NITF", "text/vnd.IPTC.NITF"},		// 'vnd.IPTC.NITF' from reference [IPTC]
    {"vnd.latex-z", "text/vnd.latex-z"},		// 'vnd.latex-z' from reference [Mikusiak_Lubos]
    {"vnd.motorola.reflex", "text/vnd.motorola.reflex"},		// 'vnd.motorola.reflex' from reference [Mark_Patton]
    {"vnd.ms-mediapackage", "text/vnd.ms-mediapackage"},		// 'vnd.ms-mediapackage' from reference [Jan_Nelson]
    {"vnd.net2phone.commcenter.command", "text/vnd.net2phone.commcenter.command"},		// 'vnd.net2phone.commcenter.command' from reference [Feiyu_Xie]
    {"vnd.radisys.msml-basic-layout", "text/vnd.radisys.msml-basic-layout"},		// 'vnd.radisys.msml-basic-layout' from reference [RFC5707]
    {"vnd.senx.warpscript", "text/vnd.senx.warpscript"},		// 'vnd.senx.warpscript' from reference [Pierre_Papin]
    {"vnd.si.uricatalogue (OBSOLETED by request)", "text/vnd.si.uricatalogue"},		// 'vnd.si.uricatalogue (OBSOLETED by request)' from reference [Nicholas_Parks_Young]
    {"vnd.sun.j2me.app-descriptor", "text/vnd.sun.j2me.app-descriptor"},		// 'vnd.sun.j2me.app-descriptor' from reference [Gary_Adams]
    {"vnd.sosi", "text/vnd.sosi"},		// 'vnd.sosi' from reference [Petter_Reinholdtsen]
    {"vnd.typst", "text/vnd.typst"},		// 'vnd.typst' from reference [Martin_Haug]
    {"vnd.trolltech.linguist", "text/vnd.trolltech.linguist"},		// 'vnd.trolltech.linguist' from reference [David_Lee_Lambert]
    {"vnd.vcf", "text/vnd.vcf"},		// 'vnd.vcf' from reference [Anand_Jahagirdar]
    {"vnd.wap.si", "text/vnd.wap.si"},		// 'vnd.wap.si' from reference [WAP-Forum]
    {"vnd.wap.sl", "text/vnd.wap.sl"},		// 'vnd.wap.sl' from reference [WAP-Forum]
    {"vnd.wap.wml", "text/vnd.wap.wml"},		// 'vnd.wap.wml' from reference [Peter_Stark]
    {"vnd.wap.wmlscript", "text/vnd.wap.wmlscript"},		// 'vnd.wap.wmlscript' from reference [Peter_Stark]
    {"vnd.zoo.kcl", "text/vnd.zoo.kcl"},		// 'vnd.zoo.kcl' from reference [Jessie_Frazelle]
    {"vtt", "text/vtt"},		// 'vtt' from reference [W3C][Silvia_Pfeiffer]
    {"wgsl", "text/wgsl"},		// 'wgsl' from reference [W3C][David_Neto]
    {"xml", "text/xml"},		// 'xml' from reference [RFC7303]
    {"xml-external-parsed-entity", "text/xml-external-parsed-entity"},		// 'xml-external-parsed-entity' from reference [RFC7303]
	};
}