namespace Hamfer.WebApi.Core.ContentTypes;

// Video data or files, such as MP4 movies.
// https://www.iana.org/assignments/media-types/media-types.xhtml#video
// To use csv: ^([^,]+),(video/[a-z0-9+-_]+),(.+)$	=>	\t"$1": "$2",\t\t// '$1' from reference $3
// last updated as 2025-12-25
public static class VideoContentTypes
{
	public static readonly Dictionary<string, string> ContentTypes = new()
	{
    {"1d-interleaved-parityfec", "video/1d-interleaved-parityfec"},		// '1d-interleaved-parityfec' from reference [RFC6015]
    {"3gpp", "video/3gpp"},		// '3gpp' from reference [RFC3839][RFC6381]
    {"3gpp2", "video/3gpp2"},		// '3gpp2' from reference [RFC4393][RFC6381]
    {"3gpp-tt", "video/3gpp-tt"},		// '3gpp-tt' from reference [RFC4396]
    {"AV1", "video/AV1"},		// 'AV1' from reference [Alliance_for_Open_Media]
    {"BMPEG", "video/BMPEG"},		// 'BMPEG' from reference [RFC3555]
    {"BT656", "video/BT656"},		// 'BT656' from reference [RFC3555]
    {"CelB", "video/CelB"},		// 'CelB' from reference [RFC3555]
    {"DV", "video/DV"},		// 'DV' from reference [RFC6469]
    {"encaprtp", "video/encaprtp"},		// 'encaprtp' from reference [RFC6849]
    {"evc", "video/evc"},		// 'evc' from reference [RFC9584]
    {"example", "video/example"},		// 'example' from reference [RFC4735]
    {"FFV1", "video/FFV1"},		// 'FFV1' from reference [RFC9043]
    {"flexfec", "video/flexfec"},		// 'flexfec' from reference [RFC8627]
    {"H261", "video/H261"},		// 'H261' from reference [RFC4587]
    {"H263", "video/H263"},		// 'H263' from reference [RFC3555]
    {"H263-1998", "video/H263-1998"},		// 'H263-1998' from reference [RFC4629]
    {"H263-2000", "video/H263-2000"},		// 'H263-2000' from reference [RFC4629]
    {"H264", "video/H264"},		// 'H264' from reference [RFC6184]
    {"H264-RCDO", "video/H264-RCDO"},		// 'H264-RCDO' from reference [RFC6185]
    {"H264-SVC", "video/H264-SVC"},		// 'H264-SVC' from reference [RFC6190]
    {"H265", "video/H265"},		// 'H265' from reference [RFC7798]
    {"H266", "video/H266"},		// 'H266' from reference [RFC9328]
    {"iso.segment", "video/iso.segment"},		// 'iso.segment' from reference [David_Singer][ISO-IEC_JTC_1]
    {"JPEG", "video/JPEG"},		// 'JPEG' from reference [RFC3555]
    {"jpeg2000", "video/jpeg2000"},		// 'jpeg2000' from reference [RFC5371][RFC5372]
    {"jpeg2000-scl", "video/jpeg2000-scl"},		// 'jpeg2000-scl' from reference [RFC9828]
    {"jxsv", "video/jxsv"},		// 'jxsv' from reference [RFC9134]
    {"lottie+json", "video/lottie+json"},		// 'lottie+json' from reference [Lottie_Animation_Community]
    {"matroska", "video/matroska"},		// 'matroska' from reference [RFC9559]
    {"matroska-3d", "video/matroska-3d"},		// 'matroska-3d' from reference [RFC9559]
    {"mj2", "video/mj2"},		// 'mj2' from reference [RFC3745]
    {"MP1S", "video/MP1S"},		// 'MP1S' from reference [RFC3555]
    {"MP2P", "video/MP2P"},		// 'MP2P' from reference [RFC3555]
    {"MP2T", "video/MP2T"},		// 'MP2T' from reference [RFC3555]
    {"mp4", "video/mp4"},		// 'mp4' from reference [RFC4337][RFC6381]
    {"MP4V-ES", "video/MP4V-ES"},		// 'MP4V-ES' from reference [RFC6416]
    {"MPV", "video/MPV"},		// 'MPV' from reference [RFC3555]
    {"mpeg", "video/mpeg"},		// 'mpeg' from reference [RFC2045][RFC2046]
    {"mpeg4-generic", "video/mpeg4-generic"},		// 'mpeg4-generic' from reference [RFC3640]
    {"nv", "video/nv"},		// 'nv' from reference [RFC4856]
    {"ogg", "video/ogg"},		// 'ogg' from reference [RFC5334][RFC7845]
    {"parityfec", "video/parityfec"},		// 'parityfec' from reference [RFC3009]
    {"pointer", "video/pointer"},		// 'pointer' from reference [RFC2862]
    {"quicktime", "video/quicktime"},		// 'quicktime' from reference [RFC6381][Paul_Lindner]
    {"raptorfec", "video/raptorfec"},		// 'raptorfec' from reference [RFC6682]
    {"raw", "video/raw"},		// 'raw' from reference [RFC4175]
    {"rtp-enc-aescm128", "video/rtp-enc-aescm128"},		// 'rtp-enc-aescm128' from reference [_3GPP]
    {"rtploopback", "video/rtploopback"},		// 'rtploopback' from reference [RFC6849]
    {"rtx", "video/rtx"},		// 'rtx' from reference [RFC4588]
    {"scip", "video/scip"},		// 'scip' from reference [RFC9607]
    {"smpte291", "video/smpte291"},		// 'smpte291' from reference [RFC8331]
    {"SMPTE292M", "video/SMPTE292M"},		// 'SMPTE292M' from reference [RFC3497]
    {"ulpfec", "video/ulpfec"},		// 'ulpfec' from reference [RFC5109]
    {"vc1", "video/vc1"},		// 'vc1' from reference [RFC4425]
    {"vc2", "video/vc2"},		// 'vc2' from reference [RFC8450]
    {"vnd.blockfact.factv", "video/vnd.blockfact.factv"},		// 'vnd.blockfact.factv' from reference [Egbert_von_Frankenberg]
    {"vnd.CCTV", "video/vnd.CCTV"},		// 'vnd.CCTV' from reference [Frank_Rottmann]
    {"vnd.dece.hd", "video/vnd.dece.hd"},		// 'vnd.dece.hd' from reference [Michael_A_Dolan]
    {"vnd.dece.mobile", "video/vnd.dece.mobile"},		// 'vnd.dece.mobile' from reference [Michael_A_Dolan]
    {"vnd.dece.mp4", "video/vnd.dece.mp4"},		// 'vnd.dece.mp4' from reference [Michael_A_Dolan]
    {"vnd.dece.pd", "video/vnd.dece.pd"},		// 'vnd.dece.pd' from reference [Michael_A_Dolan]
    {"vnd.dece.sd", "video/vnd.dece.sd"},		// 'vnd.dece.sd' from reference [Michael_A_Dolan]
    {"vnd.dece.video", "video/vnd.dece.video"},		// 'vnd.dece.video' from reference [Michael_A_Dolan]
    {"vnd.directv.mpeg", "video/vnd.directv.mpeg"},		// 'vnd.directv.mpeg' from reference [Nathan_Zerbe]
    {"vnd.directv.mpeg-tts", "video/vnd.directv.mpeg-tts"},		// 'vnd.directv.mpeg-tts' from reference [Nathan_Zerbe]
    {"vnd.dlna.mpeg-tts", "video/vnd.dlna.mpeg-tts"},		// 'vnd.dlna.mpeg-tts' from reference [Edwin_Heredia]
    {"vnd.dvb.file", "video/vnd.dvb.file"},		// 'vnd.dvb.file' from reference [Peter_Siebert][Kevin_Murray]
    {"vnd.fvt", "video/vnd.fvt"},		// 'vnd.fvt' from reference [Arild_Fuldseth]
    {"vnd.hns.video", "video/vnd.hns.video"},		// 'vnd.hns.video' from reference [Swaminathan]
    {"vnd.iptvforum.1dparityfec-1010", "video/vnd.iptvforum.1dparityfec-1010"},		// 'vnd.iptvforum.1dparityfec-1010' from reference [Shuji_Nakamura]
    {"vnd.iptvforum.1dparityfec-2005", "video/vnd.iptvforum.1dparityfec-2005"},		// 'vnd.iptvforum.1dparityfec-2005' from reference [Shuji_Nakamura]
    {"vnd.iptvforum.2dparityfec-1010", "video/vnd.iptvforum.2dparityfec-1010"},		// 'vnd.iptvforum.2dparityfec-1010' from reference [Shuji_Nakamura]
    {"vnd.iptvforum.2dparityfec-2005", "video/vnd.iptvforum.2dparityfec-2005"},		// 'vnd.iptvforum.2dparityfec-2005' from reference [Shuji_Nakamura]
    {"vnd.iptvforum.ttsavc", "video/vnd.iptvforum.ttsavc"},		// 'vnd.iptvforum.ttsavc' from reference [Shuji_Nakamura]
    {"vnd.iptvforum.ttsmpeg2", "video/vnd.iptvforum.ttsmpeg2"},		// 'vnd.iptvforum.ttsmpeg2' from reference [Shuji_Nakamura]
    {"vnd.motorola.video", "video/vnd.motorola.video"},		// 'vnd.motorola.video' from reference [Tom_McGinty]
    {"vnd.motorola.videop", "video/vnd.motorola.videop"},		// 'vnd.motorola.videop' from reference [Tom_McGinty]
    {"vnd.mpegurl", "video/vnd.mpegurl"},		// 'vnd.mpegurl' from reference [Heiko_Recktenwald]
    {"vnd.ms-playready.media.pyv", "video/vnd.ms-playready.media.pyv"},		// 'vnd.ms-playready.media.pyv' from reference [Steve_DiAcetis]
    {"vnd.nokia.interleaved-multimedia", "video/vnd.nokia.interleaved-multimedia"},		// 'vnd.nokia.interleaved-multimedia' from reference [Petteri_Kangaslampi]
    {"vnd.nokia.mp4vr", "video/vnd.nokia.mp4vr"},		// 'vnd.nokia.mp4vr' from reference [Miska_M._Hannuksela]
    {"vnd.nokia.videovoip", "video/vnd.nokia.videovoip"},		// 'vnd.nokia.videovoip' from reference [Nokia]
    {"vnd.objectvideo", "video/vnd.objectvideo"},		// 'vnd.objectvideo' from reference [John_Clark]
    {"vnd.planar", "video/vnd.planar"},		// 'vnd.planar' from reference [David_Atkins]
    {"vnd.radgamettools.bink", "video/vnd.radgamettools.bink"},		// 'vnd.radgamettools.bink' from reference [Henrik_Andersson]
    {"vnd.radgamettools.smacker", "video/vnd.radgamettools.smacker"},		// 'vnd.radgamettools.smacker' from reference [Henrik_Andersson]
    {"vnd.sealed.mpeg1", "video/vnd.sealed.mpeg1"},		// 'vnd.sealed.mpeg1' from reference [David_Petersen]
    {"vnd.sealed.mpeg4", "video/vnd.sealed.mpeg4"},		// 'vnd.sealed.mpeg4' from reference [David_Petersen]
    {"vnd.sealed.swf", "video/vnd.sealed.swf"},		// 'vnd.sealed.swf' from reference [David_Petersen]
    {"vnd.sealedmedia.softseal.mov", "video/vnd.sealedmedia.softseal.mov"},		// 'vnd.sealedmedia.softseal.mov' from reference [David_Petersen]
    {"vnd.uvvu.mp4", "video/vnd.uvvu.mp4"},		// 'vnd.uvvu.mp4' from reference [Michael_A_Dolan]
    {"vnd.youtube.yt", "video/vnd.youtube.yt"},		// 'vnd.youtube.yt' from reference [Google]
    {"vnd.vivo", "video/vnd.vivo"},		// 'vnd.vivo' from reference [John_Wolfe]
    {"VP8", "video/VP8"},		// 'VP8' from reference [RFC7741]
    {"VP9", "video/VP9"},		// 'VP9' from reference [RFC9628]
	};
}